### ISSUE TITLE
Monitoring Spending

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#78]
We need to monitor our spending and find ways to improve where possible

**Comment by rhiananthony** [comment]
Kylee - June 19, 2018 - 11:21AM
Monitoring on main AWS account, not on GCP accounts. Let's revisit later this summer.


Kylee - Mar 27, 2018 - 11:27PM
from a comment Andrey made:
While AWS has good tools for cost monitoring and alerting, GCP's tools are correspondingly awful (in fact, as far as I can tell, nonexistent). We will need to find a third-party cost monitoring tool to use for GCP, as we currently have no way at all to monitor GCP costs (after looking through Google's products bundled into the GCP console).


Sam - Mar 13, 2018 - 1:37PM
Note that when we pass $20,000 / month spend on GCP, we will need to flag this with CZI ops so we can switch from credit-card to invoice payments.


Kylee - Mar 13, 2018 - 11:37AM
AWS has a great way to monitor this, and Andrey will lead on that. Kylee sync with anyone you can to get information on monitoring for spending on GCP and put here.

**Comment by stahiri** [comment]
As discussed in the last DevSecOps meeting, this is not a prioritized objective on the Q3 roadmap but is in the list for Q4 prioritization. I've updated the GA release tag with Q4.

**Comment by brianraymor** [comment]
@stahiri and @mweiden - can the Release be cleared and this issue moved to the _Icebox_ until it is a priority for a Release?

**Comment by stahiri** [comment]
I believe so, as @kislyuk previously indicated that the **immediate** need has been addressed.

**Comment by mweiden** [comment]
@brianraymor I will move this to the icebox for now. We still have some work let to do here.
